### ISSUE TITLE
Add linting configuration as we have it in the Header project

### ISSUE THREAD

**Issue by orlando** [debtcollective/dispute-tools#175]
We want to have the same configuration for linting across all of our projects. We did this initial build in the header repository. We want to port that configuration to this repository too.

## Acceptance Criteria

- Linting and git hooks should work as it works in the Header

**Comment by duranmla** [comment]
This ticket may be in the wrong repo, we need this on Disputes project

**Comment by orlando** [comment]
Issue moved to [debtcollective/disputes #59](https://github.com/debtcollective/disputes/issues/59) via [**ZenHub**](https://www.zenhub.com/)
