### ISSUE TITLE
Sign Up screen does not full display on phones

### ISSUE THREAD

**Issue by orlando** [debtcollective/dispute-tools#186]
@dawn3296 commented on [Tue Jul 16 2019](https://github.com/debtcollective/parent/issues/272)

Seen on 3 different mobile devices. All Android platforms. Not sure what browser on the phones.

1. When you access the home page. screen does not show that you need to scroll over to the right to see the "login" button.

2. Signing screen cuts of the first field title 'EMAIL ADDRESS
user gets to bottom and clicks submit. Comes back with an error, and highlights first field. but you cannot see what is it asking for.

![Capture+_2019-07-16-07-49-04](https://user-images.githubusercontent.com/42922071/61324912-556cc400-a7c8-11e9-9d0f-0c99ec28bf0b.png)
![Capture+_2019-07-16-07-49-40](https://user-images.githubusercontent.com/42922071/61324914-556cc400-a7c8-11e9-9288-df69f43e127d.png)

---

@dawn3296 commented on [Tue Jul 16 2019](https://github.com/debtcollective/parent/issues/272#issuecomment-511961679)

The circled blue section is all you see from the screen.

![image](https://user-images.githubusercontent.com/42922071/61325111-dc21a100-a7c8-11e9-92d6-a95a195d3783.png)

**Comment by duranmla** [comment]
The issues within the landing has been solved with the latest refactor. CMD + SHIFT + R, everything should behave as expected. I can take a look to the community

**Comment by orlando** [comment]
Cool, I'll assign you this ticket, we can use https://browserstack.com to replicate the issue with the signup modal in Discourse.

**Comment by orlando** [comment]
We are running the latest version of Discourse in the community atm. Here's are some videos about the issue.

https://www.loom.com/share/076917b2fa1d4d9784eef09573c26844
https://www.loom.com/share/cbcf2cdcdd6e4feeb8c681ffcd8df290

**Comment by duranmla** [comment]
Keeping the updates here the conclusion is that:

- We update the Discourse to latest to get the new styling modifications from the core team.
- While now all the inputs are visible the whole modal behaviour is buggy related to the scrolling _(which is possible to do but it doesn't behave as expected, more info on the videos)_
- The modal still cropped on the top for few pixels

I will take a look to the scrolling issue within the signup.
