### ISSUE TITLE
Incorrect steps show on dispute information page before starting a dispute

### ISSUE THREAD

**Issue by marcondag** [debtcollective/dispute-tools#21]
## Steps to reproduce

1) Navigate to `/dispute-tools` and click the link to begin a general debt dispute, loading the information page
2) Make note of the number of steps (5)
3) Click the "Begin dispute" button

## Expected results

The number of steps on the left should not be different from the steps displayed on the information page for the dispute tool

## Actual results

The steps are different. See screenshots

<img width="1184" alt="screen shot 2018-04-15 at 7 03 40 pm" src="https://user-images.githubusercontent.com/24264157/38784437-cc481b8e-40df-11e8-91f4-4fb0f770b3d4.png">

<img width="1180" alt="screen shot 2018-04-15 at 7 03 49 pm" src="https://user-images.githubusercontent.com/24264157/38784439-d5943902-40df-11e8-9176-278e12980933.png">

**Comment by orlando** [comment]
Issue moved to [debtcollective/parent #115](https://github.com/debtcollective/parent/issues/115) via [**ZenHub**](https://www.zenhub.com/)

**Comment by orlando** [comment]
Issue moved to [debtcollective/parent #116](https://github.com/debtcollective/parent/issues/116) via [**ZenHub**](https://www.zenhub.com/)
